name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: >
        sudo apt install
        libudev-dev

    - name: Build
      run: cargo build --release

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: stm32-opts-ubuntu-latest
        path: ${{ github.workspace }}/target/release/stm32-opts
